name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dep
        run: make inst

      - name: Setup env
        run: . ./test/setenv.sh

      - name: Test
        env:
          GOPATH: /home/runner/work/
        run: make test
