name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
          IBM_DB_HOME: ./clidriver/
          CGO_CFLAGS: -I./clidriver/include/
          CGO_LDFLAGS: -L./clidriver/lib/
          DYLD_LIBRARY_PATH: ./clidriver/lib/
        run: make test
