name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: make test
        env:
          IBM_DB_HOME: `pwd`/clidriver
          CGO_CFLAGS: -I$IBM_DB_HOME/include
          CGO_LDFLAGS: -L$IBM_DB_HOME/lib
          DYLD_LIBRARY_PATH: $IBM_DB_HOME/lib:$DYLD_LIBRARY_PATH
          PATH: $PATH:$IBM_DB_HOME/bin
