name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      #- name: Additional env
      #  run: export LD_LIBRARY_PATH=$IBM_DB_HOME/lib:$LD_LIBRARY_PATH
      - name: Test
        env:
          IBM_DB_HOME: /home/runner/go/clidriver
          CGO_CFLAGS: -I/home/runner/go/clidriver/include
          CGO_LDFLAGS: -L/home/runner/go/clidriver/lib
          #DYLD_LIBRARY_PATH: /home/runner/go/clidriver/lib
        run: make test
